name:                alien-expedition
version:             0.1.0.0
github:              "mgajda/alien-expedition"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "AllRightsReserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjgajda/alien-expedition#readme>

dependencies:
- base >= 4.7 && < 5
- restartable
- sdl2
- sdl2-image
- sdl2-mixer
- sdl2-ttf
- apecs
- text
- optics
- optics-th

library:
  source-dirs: src

executables:
  alien-expedition-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alien-expedition
    - random # temporary

tests:
  alien-expedition-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alien-expedition
    - QuickCheck
    - quickcheck-classes
    - less-arbitrary
